index:
    path: /
    controller: App\Controller\DefaultController::index
logo:
    path: /build/images/logo-hopital.gif
    controller: App\Controller\DefaultController::logo
css:
    path: /build/css/style.css
    controller: App\Controller\DefaultController::css